In [23]:
import requests
import json
import pandas as pd
import numpy as np
import datetime
import calendar
from config import bls_api_key
import gmaps
from test_key import g_key

In [24]:
start_year = "2006"
end_year = "2018"
g_start_year_1="2008"
g_end_year_1="2011"
g_start_year_2="2012"
g_end_year_2="2018"

## Demographic BLS Data Pull

In [94]:
url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
headers = {"content-type": "application/json"}

target_series = ["LNS14000000", "LNS14000001", "LNS14000002", "LNS14000003", "LNS14000004", "LNS14000005",
                 "LNS14000006", "LNS14000007", "LNS14000008", "LNS14032183", "LNS14000009", "LNS14000012",
                 "LNS14000013", "LNS14000014", "LNS14000015", "LNS14000016", "LNS14000017", "LNS14000018",
                 "LNS14000019", "LNS14000020", "LNS14000021", "LNS14000022", "LNS14000023", "LNS14000036",
                 "LNS14000037", "LNS14000038", "LNS14000089", "LNS14000164", "LNS14000327", "LNS14000091",
                 "LNS14000173", "LNS14000334", "LNS14000093", "LNS14000182", "LNS14000341", "LNS14024230",
                 "LNS14024231", "LNS14024232", "LNS14000048", "LNS14000049", "LNS14000050", "LNS14027659",
                 "LNS14027660", "LNS14027689", "LNS14027662", "LNS14000024", "LNS14000025", "LNS14000026",
                 "LNS14000027", "LNS14000028"]


parameters = json.dumps({"seriesid": target_series,
             "startyear": start_year,
             "endyear": end_year,
             "registrationkey": bls_api_key})

p = requests.post(url, data=parameters, headers=headers)

json_data5 = json.loads(p.text)

In [95]:
url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
headers = {"content-type": "application/json"}

target_series = ["LNS14000029", "LNS14000030", "LNS14000031", "LNS14000032",
                 "LNS14000033", "LNS14000034", "LNS14000035", "LNS14024887"]


parameters = json.dumps({"seriesid": target_series,
             "startyear": start_year,
             "endyear": end_year,
             "registrationkey": bls_api_key})

p = requests.post(url, data=parameters, headers=headers)

json_data6 = json.loads(p.text)

In [140]:
Year = []
date = []

for data_point in np.arange(len(json_data5["Results"]["series"][0]["data"])):
        Year.append(f"{json_data5['Results']['series'][0]['data'][data_point]['year']}")
        date.append(f"{json_data5['Results']['series'][0]['data'][data_point]['year']}-{json_data5['Results']['series'][0]['data'][data_point]['period'][1:]}")

In [141]:
unemployment_df = pd.DataFrame({"Date": date, "Year": Year,
                                "LNS14000000": "", "LNS14000001": "", "LNS14000002": "",
                                "LNS14000003": "", "LNS14000004": "", "LNS14000005": "",
                                "LNS14000006": "", "LNS14000007": "", "LNS14000008": "",
                                "LNS14032183": "", "LNS14000009": "", "LNS14000012": "",
                                "LNS14000013": "", "LNS14000014": "", "LNS14000015": "",
                                "LNS14000016": "", "LNS14000017": "", "LNS14000018": "",
                                "LNS14000019": "", "LNS14000020": "", "LNS14000021": "",
                                "LNS14000022": "", "LNS14000023": "", "LNS14000024": "",
                                "LNS14000025": "", "LNS14000026": "", "LNS14000027": "",
                                "LNS14000028": "", "LNS14000029": "", "LNS14000030": "",
                                "LNS14000031": "", "LNS14000032": "", "LNS14000033": "",
                                "LNS14000034": "", "LNS14000035": "", "LNS14024887": "",
                                "LNS14000036": "", "LNS14000037": "", "LNS14000038": "",
                                "LNS14000089": "", "LNS14000164": "", "LNS14000327": "",
                                "LNS14000091": "", "LNS14000173": "", "LNS14000334": "",
                                "LNS14000093": "", "LNS14000182": "", "LNS14000341": "",
                                "LNS14024230": "", "LNS14024231": "", "LNS14024232": "",
                                "LNS14000048": "", "LNS14000049": "", "LNS14000050": "",
                                "LNS14027659": "", "LNS14027660": "", "LNS14027689": "",
                                "LNS14027662": ""})

unemployment_df.head()

,Date,Year,LNS14000000,LNS14000001,LNS14000002,LNS14000003,LNS14000004,LNS14000005,LNS14000006,LNS14000007,...,LNS14024230,LNS14024231,LNS14024232,LNS14000048,LNS14000049,LNS14000050,LNS14027659,LNS14027660,LNS14027689,LNS14027662
0,2018-12,2018,,,,,,,,,...,,,,,,,,,,
1,2018-11,2018,,,,,,,,,...,,,,,,,,,,
2,2018-10,2018,,,,,,,,,...,,,,,,,,,,
3,2018-09,2018,,,,,,,,,...,,,,,,,,,,
4,2018-08,2018,,,,,,,,,...,,,,,,,,,,

In [142]:
for series5 in np.arange(len(json_data5["Results"]["series"])):
    for data_point5 in np.arange(len(json_data5["Results"]["series"][series5]["data"])):
        unemployment_df.loc[data_point5, json_data5["Results"]["series"][series5]["seriesID"]] = json_data5["Results"]["series"][series5]["data"][data_point5]["value"]

for series in np.arange(len(json_data6["Results"]["series"])):
    for data_point in np.arange(len(json_data6["Results"]["series"][series]["data"])):
        unemployment_df.loc[data_point, json_data6["Results"]["series"][series]["seriesID"]] = json_data6["Results"]["series"][series]["data"][data_point]["value"]

In [143]:
for column in unemployment_df.columns[3:]:
    unemployment_df[f"{column}"] = unemployment_df[f"{column}"].astype(float)

In [111]:
layoffsInd_I_df = unemployment_df.loc[:,["Date",
                           "LNS14000000", 
                           "LNS14000001", 
                           "LNS14000002", 
                           "LNS14000003", 
                           "LNS14000006", 
                           "LNS14032183",
                           "LNS14000009",
                           "LNS14027659", 
                           "LNS14027660", 
                           "LNS14027689",
                           "LNS14027662", 
                           "LNS14024887",
                           "LNS14000089",
                           "LNS14000091",
                           "LNS14000093",
                           "LNS14024230"]]

In [112]:
#fill fit year and month into columns
years = []
months = []
periods = []
dates = []

for data_point in np.arange(len(json_data5["Results"]["series"][0]["data"])):
        years.append(json_data5["Results"]["series"][0]["data"][data_point]["year"])
        periods.append(json_data5["Results"]["series"][0]["data"][data_point]["period"])
        months.append(json_data5["Results"]["series"][0]["data"][data_point]["periodName"])
        dates.append(f"{json_data5['Results']['series'][0]['data'][data_point]['year']}-{json_data5['Results']['series'][0]['data'][data_point]['period'][1:]}")

In [113]:
layoffsInd_df = pd.DataFrame({"Years": years,
                           "Periods": periods,
                           "Months": months,
                            "Date": dates})
layoffsInd_df = pd.merge(layoffsInd_df, layoffsInd_I_df, on="Date", how="outer")
layoffsInd_df = layoffsInd_df.drop(["Date"], axis=1)
layoffsInd_df.head()

,Years,Periods,Months,LNS14000000,LNS14000001,LNS14000002,LNS14000003,LNS14000006,LNS14032183,LNS14000009,LNS14027659,LNS14027660,LNS14027689,LNS14027662,LNS14024887,LNS14000089,LNS14000091,LNS14000093,LNS14024230
0,2018,M12,December,3.9,3.9,3.8,3.4,6.6,3.3,4.4,5.8,3.8,3.3,2.2,8.7,3.9,2.8,2.9,2.9
1,2018,M11,November,3.7,3.6,3.8,3.4,6.1,2.8,4.5,5.6,3.5,3.1,2.2,8.2,3.7,2.9,2.7,2.8
2,2018,M10,October,3.8,3.8,3.8,3.3,6.3,3.1,4.4,5.9,4.0,3.1,2.0,8.4,3.7,3.0,2.8,2.8
3,2018,M09,September,3.7,3.8,3.7,3.3,6.2,3.5,4.6,5.7,3.8,3.2,2.0,8.6,3.6,3.0,2.6,2.8
4,2018,M08,August,3.8,3.8,3.8,3.4,6.3,3.0,4.7,5.7,3.9,3.5,2.0,8.5,4.1,2.8,2.5,3.0

In [147]:
unemployment_age_I_df = unemployment_df.loc[:,["Date",
                           "LNS14000000",
                           "LNS14000001",
                           "LNS14000002",
                           "LNS14000003",
                           "LNS14000006",
                           "LNS14032183",
                           "LNS14000009"]]
unemployment_age_I_df

,Date,LNS14000000,LNS14000001,LNS14000002,LNS14000003,LNS14000006,LNS14032183,LNS14000009
0,2018-12,3.9,3.9,3.8,3.4,6.6,3.3,4.4
1,2018-11,3.7,3.6,3.8,3.4,6.1,2.8,4.5
2,2018-10,3.8,3.8,3.8,3.3,6.3,3.1,4.4
3,2018-09,3.7,3.8,3.7,3.3,6.2,3.5,4.6
4,2018-08,3.8,3.8,3.8,3.4,6.3,3.0,4.7
...,...,...,...,...,...,...,...,...
151,2006-05,4.6,4.7,4.5,4.1,8.7,3.3,5.0
152,2006-04,4.7,4.7,4.7,4.1,9.4,3.9,5.5
153,2006-03,4.7,4.7,4.7,4.0,9.5,3.5,5.2
154,2006-02,4.8,4.8,4.8,4.1,9.5,3.0,5.4
155,2006-01,4.7,4.6,4.8,4.1,8.9,3.0,5.5

In [148]:
years = []
months = []
dates = []

for data_point in np.arange(len(json_data5["Results"]["series"][0]["data"])):
        years.append(json_data5["Results"]["series"][0]["data"][data_point]["year"])
        months.append(json_data5["Results"]["series"][0]["data"][data_point]["periodName"])
        dates.append(f"{json_data5['Results']['series'][0]['data'][data_point]['year']}-{json_data5['Results']['series'][0]['data'][data_point]['period'][1:]}")

In [151]:
unemployment_agedf = pd.DataFrame({"years": years,
                           "months": months,
                            "Date": dates})
unemployment_agedf = pd.merge(unemployment_agedf, unemployment_age_I_df, on="Date", how="outer")
unemployment_agedf = unemployment_agedf.drop(["Date"],axis=1)
unemployment_agedf.head()

,years,months,LNS14000000,LNS14000001,LNS14000002,LNS14000003,LNS14000006,LNS14032183,LNS14000009
0,2018,December,3.9,3.9,3.8,3.4,6.6,3.3,4.4
1,2018,November,3.7,3.6,3.8,3.4,6.1,2.8,4.5
2,2018,October,3.8,3.8,3.8,3.3,6.3,3.1,4.4
3,2018,September,3.7,3.8,3.7,3.3,6.2,3.5,4.6
4,2018,August,3.8,3.8,3.8,3.4,6.3,3.0,4.7

In [119]:
unemployment_df = unemployment_df.rename(columns={"LNS14000000": "Unemployment Rate, 16yo and over",
                                                  "LNS14000001": "Unemployment Rate, Men, 16yo and over",
                                                  "LNS14000002": "Unemployment Rate, Women, 16yo and over",
                                                  "LNS14000003": "Unemployment Rate, White, 16yo and over",
                                                  "LNS14000004": "Unemployment Rate, White, Men, 16yo and over",
                                                  "LNS14000005": "Unemployment Rate, White, Women, 16yo and over",
                                                  "LNS14000006": "Unemployment Rate, African American, 16yo and over",
                                                  "LNS14000007": "Unemployment Rate, African American, Men, 16yo and over",
                                                  "LNS14000008": "Unemployment Rate, African American, Women, 16yo and over",
                                                  "LNS14032183": "Unemployment Rate, Asian, 16yo and over",
                                                  "LNS14000009": "Unemployment Rate, Hispanic or Latino, 16yo and over",
                                                  "LNS14000012": "Unemployment Rate, 16-19yo",
                                                  "LNS14000013": "Unemployment Rate, Men, 16-19yo",
                                                  "LNS14000014": "Unemployment Rate, Women, 16-19yo",
                                                  "LNS14000015": "Unemployment Rate, White, 16-19yo",
                                                  "LNS14000016": "Unemployment Rate, White, Men, 16-19yo",
                                                  "LNS14000017": "Unemployment Rate, White, Women, 16-19yo",
                                                  "LNS14000018": "Unemployment Rate, African American, 16-19yo",
                                                  "LNS14000019": "Unemployment Rate, African American, Men, 16-19yo",
                                                  "LNS14000020": "Unemployment Rate, African American, Women, 16-19yo",
                                                  "LNS14000021": "Unemployment Rate, Hispanic or Latino, 16-19yo",
                                                  "LNS14000022": "Unemployment Rate, Hispanic or Latino, Men, 16-19yo",
                                                  "LNS14000023": "Unemployment Rate, Hispanic or Latino, Women, 16-19yo",
                                                  "LNS14000024": "Unemployment Rate, 20yo and over",
                                                  "LNS14000025": "Unemployment Rate, Men, 20yo and over",
                                                  "LNS14000026": "Unemployment Rate, Women, 20yo and over",
                                                  "LNS14000027": "Unemployment Rate, White, 20yo and over",
                                                  "LNS14000028": "Unemployment Rate, White, Men, 20yo and over",
                                                  "LNS14000029": "Unemployment Rate, White, Women, 20yo and over",
                                                  "LNS14000030": "Unemployment Rate, African American, 20yo and over",
                                                  "LNS14000031": "Unemployment Rate, African American, Men, 20yo and over",
                                                  "LNS14000032": "Unemployment Rate, African American, Women, 20yo and over",
                                                  "LNS14000033": "Unemployment Rate, Hispanic or Latino, 20yo and over",
                                                  "LNS14000034": "Unemployment Rate, Hispanic or Latino, Men, 20yo and over",
                                                  "LNS14000035": "Unemployment Rate, Hispanic or Latino, Women, 20yo and over",
                                                  "LNS14024887": "Unemployment Rate, 16-24yo",
                                                  "LNS14000036": "Unemployment Rate, 20-24yo",
                                                  "LNS14000037": "Unemployment Rate, Men, 20-24yo",
                                                  "LNS14000038": "Unemployment Rate, Women, 20-24yo",
                                                  "LNS14000089": "Unemployment Rate, 25-34yo",
                                                  "LNS14000164": "Unemployment Rate, Men, 25-34yo",
                                                  "LNS14000327": "Unemployment Rate, Women, 25-34yo",
                                                  "LNS14000091": "Unemployment Rate, 35-44yo",
                                                  "LNS14000173": "Unemployment Rate, Men, 35-44yo",
                                                  "LNS14000334": "Unemployment Rate, Women, 35-44yo",
                                                  "LNS14000093": "Unemployment Rate, 45-54yo",
                                                  "LNS14000182": "Unemployment Rate, Men, 45-54yo",
                                                  "LNS14000341": "Unemployment Rate, Women, 45-54yo",
                                                  "LNS14024230": "Unemployment Rate, 55yo and over",
                                                  "LNS14024231": "Unemployment Rate, Men, 55yo and over",
                                                  "LNS14024232": "Unemployment Rate, Women, 55yo and over",
                                                  "LNS14000048": "Unemployment Rate, 25yo and over",
                                                  "LNS14000049": "Unemployment Rate, Men, 25yo and over",
                                                  "LNS14000050": "Unemployment Rate, Women, 25yo and over",
                                                  "LNS14027659": "Unemployment Rate, Less than High School diploma, 25yo and over",
                                                  "LNS14027660": "Unemployment Rate, High school-no college, 25yo and over",
                                                  "LNS14027689": "Unemployment Rate, Some college, 25yo and over",
                                                  "LNS14027662": "Unemployment Rate, Bachelor's degree or higher, 25yo and over"})


unemployment_df.sort_values(by="Date", ascending=True, inplace=True)

unemployment_df.reset_index(drop=True, inplace=True)

unemployment_df.to_csv("Combined_Ouput_File/unemployment_rate.csv", index=False)

In [11]:
pull_education_df = unemployment_df
len(pull_education_df)

156

In [12]:
educationyears = pull_education_df['Year'].unique()
educationmonthnumber = [ ]

for year in educationyears:
    educationmonth = 13
    while (educationmonth > 1): 
        educationmonth = educationmonth -1
        educationmonthnumber.append(educationmonth)
        if  educationmonth == 0:
            break
pull_education_df['Month #'] = educationmonthnumber

In [13]:
leveleducation_df = pull_education_df[['Year', 'Month #', 'Unemployment Rate, Less than High School diploma, 25yo and over',
                  'Unemployment Rate, High school-no college, 25yo and over', 
                  'Unemployment Rate, Some college, 25yo and over',
                  "Unemployment Rate, Bachelor's degree or higher, 25yo and over"]]

leveleducation_df = leveleducation_df.rename(columns={'Unemployment Rate, Less than High School diploma, 25yo and over': "No High School Diploma",
                                           'Unemployment Rate, High school-no college, 25yo and over': 'High School Graduate',
                                           'Unemployment Rate, Some college, 25yo and over': 'Some College',
                                           "Unemployment Rate, Bachelor's degree or higher, 25yo and over": "Bachelor's Degree or Higher"})

In [16]:
educationdate = []

for index, row in leveleducation_df.iterrows():
    educationdatenumber = str(f"{row['Year']}-{row['Month #']}")
    educationdate.append(educationdatenumber)

leveleducation_df['Date'] = educationdate

leveleducation_df = leveleducation_df[['Year', 'Month #', 'Date', 'No High School Diploma', 'High School Graduate',
                            'Some College', "Bachelor's Degree or Higher"]]
                     
leveleducation_df = leveleducation_df.reindex(index=leveleducation_df.index[::-1])
leveleducation_df.head()

,Year,Month #,Date,No High School Diploma,High School Graduate,Some College,Bachelor's Degree or Higher
155,2018,1,2018-1,5.8,3.8,3.3,2.2
154,2018,2,2018-2,5.6,3.5,3.1,2.2
153,2018,3,2018-3,5.9,4.0,3.1,2.0
152,2018,4,2018-4,5.7,3.8,3.2,2.0
151,2018,5,2018-5,5.7,3.9,3.5,2.0

In [17]:
leveleducation_df.to_csv("Combined_Ouput_File/level_of_education.csv")

In [30]:
educationyearinfo = leveleducation_df[['Year', 'No High School Diploma', 'High School Graduate', 'Some College', "Bachelor's Degree or Higher"]]
educationyearinfo = educationyearinfo.astype(float)
educationyearinfo['Year'] = educationyearinfo['Year'].astype(int)

In [47]:
educationyear_groupby= educationyearinfo.groupby('Year')['No High School Diploma', 'High School Graduate', 
                                       'Some College', "Bachelor's Degree or Higher"].mean()

educationyear_groupby= pd.DataFrame(educationyear_groupby)
educationyear_groupby

,No High School Diploma,High School Graduate,Some College,Bachelor's Degree or Higher
Year,,,,
2006,6.783333,4.300000,3.575000,2.025000
2007,7.133333,4.375000,3.558333,2.025000
2008,9.025000,5.683333,4.575000,2.558333
2009,14.666667,9.733333,7.958333,4.608333
2010,14.841667,10.291667,8.383333,4.708333
2011,14.075000,9.425000,7.966667,4.308333
2012,12.391667,8.308333,7.100000,4.025000
2013,10.958333,7.508333,6.366667,3.700000
2014,9.016667,6.008333,5.425000,3.175000
2015,7.941667,5.441667,4.508333,2.566667
2016,7.433333,5.191667,4.083333,2.508333
2017,6.508333,4.650000,3.750000,2.316667
2018,5.608333,4.041667,3.316667,2.125000

In [48]:
educationyear_groupby.to_csv("Combined_Ouput_File/educationyear_groupby.csv", index=True)

## Statewide Unemployment

In [120]:
url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
headers = {"content-type": "application/json"}

target_series = ["LASST010000000000003", "LASST020000000000003", "LASST040000000000003", "LASST050000000000003",
                 "LASST060000000000003", "LASST080000000000003", "LASST090000000000003", "LASST100000000000003",
                 "LASST110000000000003", "LASST120000000000003", "LASST130000000000003", "LASST150000000000003",
                 "LASST160000000000003", "LASST170000000000003", "LASST180000000000003", "LASST190000000000003",
                 "LASST200000000000003", "LASST210000000000003", "LASST220000000000003", "LASST230000000000003",
                 "LASST240000000000003", "LASST250000000000003", "LASST260000000000003", "LASST270000000000003",
                 "LASST280000000000003", "LASST290000000000003", "LASST300000000000003", "LASST310000000000003",
                 "LASST320000000000003", "LASST330000000000003", "LASST340000000000003", "LASST350000000000003",
                 "LASST360000000000003", "LASST370000000000003", "LASST380000000000003", "LASST390000000000003",
                 "LASST400000000000003", "LASST410000000000003", "LASST420000000000003", "LASST720000000000003",
                 "LASST440000000000003", "LASST450000000000003", "LASST460000000000003", "LASST470000000000003",
                 "LASST480000000000003", "LASST490000000000003", "LASST500000000000003", "LASST510000000000003",
                 "LASST530000000000003", "LASST540000000000003"]




parameters = json.dumps({"seriesid": target_series,
             "startyear": start_year,
             "endyear": end_year,
             "registrationkey": bls_api_key})

p = requests.post(url, data=parameters, headers=headers)

json_data2 = json.loads(p.text)

In [121]:
url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
headers = {"content-type": "application/json"}

target_series = ["LASST550000000000003", "LASST560000000000003"]




parameters = json.dumps({"seriesid": target_series,
             "startyear": start_year,
             "endyear": end_year,
             "registrationkey": bls_api_key})

p = requests.post(url, data=parameters, headers=headers)

json_data3 = json.loads(p.text)

In [122]:
Year = []
date = []

for data_point in np.arange(len(json_data2["Results"]["series"][0]["data"])):
        Year.append(f"{json_data2['Results']['series'][0]['data'][data_point]['year']}")
        date.append(f"{json_data2['Results']['series'][0]['data'][data_point]['year']}-{json_data2['Results']['series'][0]['data'][data_point]['period'][1:]}")

In [123]:
state_unemployment_df = pd.DataFrame({"Date": date, "Year": Year,
                                "LASST010000000000003": "", "LASST020000000000003": "", "LASST040000000000003": "",
                                "LASST050000000000003": "", "LASST060000000000003": "", "LASST080000000000003": "",
                                "LASST090000000000003": "", "LASST100000000000003": "", "LASST110000000000003": "",
                                "LASST120000000000003": "", "LASST130000000000003": "", "LASST150000000000003": "",
                                "LASST160000000000003": "", "LASST170000000000003": "", "LASST180000000000003": "",
                                "LASST190000000000003": "", "LASST200000000000003": "", "LASST210000000000003": "",
                                "LASST220000000000003": "", "LASST230000000000003": "", "LASST240000000000003": "",
                                "LASST250000000000003": "", "LASST260000000000003": "", "LASST270000000000003": "",
                                "LASST280000000000003": "", "LASST290000000000003": "", "LASST300000000000003": "",
                                "LASST310000000000003": "", "LASST320000000000003": "", "LASST330000000000003": "",
                                "LASST340000000000003": "", "LASST350000000000003": "", "LASST360000000000003": "",
                                "LASST370000000000003": "", "LASST380000000000003": "", "LASST390000000000003": "",
                                "LASST400000000000003": "", "LASST410000000000003": "", "LASST420000000000003": "",
                                "LASST720000000000003": "", "LASST440000000000003": "", "LASST450000000000003": "",
                                "LASST460000000000003": "", "LASST470000000000003": "", "LASST480000000000003": "",
                                "LASST490000000000003": "", "LASST500000000000003": "", "LASST510000000000003": "",
                                "LASST530000000000003": "", "LASST540000000000003": "", "LASST550000000000003": "",
                                "LASST560000000000003": ""})

In [124]:
for series2 in np.arange(len(json_data2["Results"]["series"])):
    for data_point2 in np.arange(len(json_data2["Results"]["series"][series2]["data"])):
        state_unemployment_df.loc[data_point2, json_data2["Results"]["series"][series2]["seriesID"]] = json_data2["Results"]["series"][series2]["data"][data_point2]["value"]

for series3 in np.arange(len(json_data3["Results"]["series"])):
    for data_point3 in np.arange(len(json_data3["Results"]["series"][series3]["data"])):
        state_unemployment_df.loc[data_point3, json_data3["Results"]["series"][series3]["seriesID"]] = json_data3["Results"]["series"][series3]["data"][data_point3]["value"]

In [125]:
for column in state_unemployment_df.columns[3:]:
    state_unemployment_df[f"{column}"] = state_unemployment_df[f"{column}"].astype(float)

state_unemployment_df.rename(columns={"LASST010000000000003" : "Alabama", "LASST020000000000003" : "Alaska",
                                      "LASST040000000000003" : "Arizona", "LASST050000000000003" : "Arkansas",
                                      "LASST060000000000003" : "California", "LASST080000000000003" : "Colorado",
                                      "LASST090000000000003" : "Connecticut", "LASST100000000000003" : "Delaware",
                                      "LASST110000000000003" : "District Of Columbia", "LASST120000000000003" : "Florida",
                                      "LASST130000000000003" : "Georgia", "LASST150000000000003" : "Hawaii",
                                      "LASST160000000000003" : "Idaho", "LASST170000000000003" : "Illinois",
                                      "LASST180000000000003" : "Indiana", "LASST190000000000003" : "Iowa",
                                      "LASST200000000000003" : "Kansas", "LASST210000000000003" : "Kentucky",
                                      "LASST220000000000003" : "Louisiana", "LASST230000000000003" : "Maine",
                                      "LASST240000000000003" : "Maryland", "LASST250000000000003" : "Massachusetts",
                                      "LASST260000000000003" : "Michigan", "LASST270000000000003" : "Minnesota",
                                      "LASST280000000000003" : "Mississippi", "LASST290000000000003" : "Missouri",
                                      "LASST300000000000003" : "Montana", "LASST310000000000003" : "Nebraska",
                                      "LASST320000000000003" : "Nevada", "LASST330000000000003" : "New Hampshire",
                                      "LASST340000000000003" : "New Jersey", "LASST350000000000003" : "New Mexico",
                                      "LASST360000000000003" : "New York", "LASST370000000000003" : "North Carolina",
                                      "LASST380000000000003" : "North Dakota", "LASST390000000000003" : "Ohio",
                                      "LASST400000000000003" : "Oklahoma", "LASST410000000000003" : "Oregon",
                                      "LASST420000000000003" : "Pennsylvania", "LASST720000000000003" : "Puerto Rico",
                                      "LASST440000000000003" : "Rhode Island", "LASST450000000000003" : "South Carolina",
                                      "LASST460000000000003" : "South Dakota", "LASST470000000000003" : "Tennessee",
                                      "LASST480000000000003" : "Texas", "LASST490000000000003" : "Utah",
                                      "LASST500000000000003" : "Vermont", "LASST510000000000003" : "Virginia",
                                      "LASST530000000000003" : "Washington", "LASST540000000000003" : "West Virginia",
                                      "LASST550000000000003" : "Wisconsin", "LASST560000000000003" : "Wyoming"},
                             inplace=True)

state_unemployment_df.sort_values(by="Date", ascending=True, inplace=True)

state_unemployment_df.reset_index(drop=True, inplace=True)

state_unemployment_df.to_csv("Combined_Ouput_File/state_unemployment_monthly.csv", index=False)

In [ ]:
state_unemployment_df_1=state_unemployment_df.iloc[24:72,:]
state_unemployment_df_1

In [ ]:
import csv

In [ ]:
with open('raw_avg.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["State", " avg1218"])
    for col in state_unemployment_df_1.columns[1:]:
        writer.writerow([col, state_unemployment_df_1[col].astype(float).mean()])

In [ ]:
import pandas as pd
avg_file="raw_avg.csv"
avg_file_df=pd.read_csv(avg_file)
avg_file_df.head(10)

In [ ]:
avg_file_df.rename(columns={"State" : "name"},inplace=True)
avg_file_df

In [ ]:
df = pd.read_csv("states.csv",delimiter="\t")
df.head()

In [ ]:
statelo_df=df
statelo_df.head()

In [ ]:
merge_df = pd.merge(statelo_df, avg_file_df, on="name")
merge_df.head(10)

In [ ]:
merge_df.to_csv("state_merge_1.csv")

In [ ]:
state_unemployment_df_2=state_unemployment_df.iloc[73:,:]
state_unemployment_df_2

In [ ]:
states_df = pd.read_csv("states.csv", delimiter="\t")
states_df=states_df.loc[states_df["name"]!="District of Columbia"]
state_names = states_df["name"]
state_unemployment_df_2[state_names] = state_unemployment_df_2[state_names].apply(pd.to_numeric)

In [ ]:
state_unemployment_df_2.dtypes

In [ ]:
state_unemployment_df_2 = state_unemployment_df_2.drop(["Date"] , axis=1)
state_unemployment_df_2 = state_unemployment_df_2.groupby("Year").mean()
state_unemployment_df_2 = state_unemployment_df_2.transpose()
state_unemployment_df_2.head()

In [ ]:
#df.rename(columns={"A": "a", "B": "c"})
state_unemployment_df_2.reset_index(inplace=True)
state_unemployment_df_2=state_unemployment_df_2.rename(columns={"index":"State"})
state_unemployment_df_2

In [ ]:
state_unemployment_df_2.set_index("State", inplace=True)

In [ ]:
state_1218_df = state_unemployment_df_2.T
#for state in state_unemployment_df_2["State"]:

state_1218_df.head(15)

In [ ]:
for col in state_1218_df.columns[1:]:
    print(col , state_1218_df[col].astype(float).mean())

In [ ]:
with open('state_avg_1218.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["State", " avg1218"])
    for col in state_1218_df.columns[1:]:
        writer.writerow([col, state_1218_df[col].astype(float).mean()])

In [ ]:
import pandas as pd
avg_file_2="Resources/state_avg_1218.csv"
avg_file_2_df=pd.read_csv(avg_file_2)
avg_file_2_df.head(10)

In [ ]:
avg_file_2_df.rename(columns={"State" : "name"},inplace=True)
avg_file_2_df.head()

In [ ]:
merge_df_2 = pd.merge(statelo_df, avg_file_2_df, on="name")
merge_df_2.head(10)

In [ ]:
merge_df_2.to_csv("state_merge_2.csv")

In [126]:
state_unemployment_y_df = state_unemployment_df.drop(["Date"], axis=1)


state_unemployment_y_df = state_unemployment_y_df.groupby("Year").mean()


state_unemployment_y_df = state_unemployment_y_df.transpose()


states_df = pd.read_csv("Resources/states.tsv", delimiter="\t")


state_unemployment_y_df = state_unemployment_y_df.rename_axis("name")
state_unemployment_y_df = pd.merge(state_unemployment_y_df, states_df, on="name", how="inner")


state_unemployment_y_df = state_unemployment_y_df.drop(["state"], axis=1)

state_unemployment_y_df.to_csv("Combined_Ouput_File/state_unempoyment_yearly.csv", index=False)

## Unemployment Level BLS Pull

In [49]:
url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
headers = {"content-type": "application/json"}

target_series = ["LNS13000000", "LNS13023621", "LNS13023653", "LNS13025699", "LNS13023705", "LNS13023557", "LNS13023569"]




parameters = json.dumps({"seriesid": target_series,
             "startyear": start_year,
             "endyear": end_year,
             "registrationkey": bls_api_key})

p = requests.post(url, data=parameters, headers=headers)

json_data4 = json.loads(p.text)

In [50]:
Year = []
date = []

for data_point in np.arange(len(json_data4["Results"]["series"][0]["data"])):
        Year.append(f"{json_data4['Results']['series'][0]['data'][data_point]['year']}")
        date.append(f"{json_data4['Results']['series'][0]['data'][data_point]['year']}-{json_data4['Results']['series'][0]['data'][data_point]['period'][1:]}")

In [51]:
layoffs_df = pd.DataFrame({"Date": date,
                           "Year": Year,
                           "LNS13000000": "",
                           "LNS13023621": "",
                           "LNS13023653": "",
                           "LNS13025699": "",
                           "LNS13023705": "",
                           "LNS13023557": "",
                           "LNS13023569": ""})

In [52]:
for series4 in np.arange(len(json_data4["Results"]["series"])):
    for data_point4 in np.arange(len(json_data4["Results"]["series"][series4]["data"])):
        layoffs_df.loc[data_point4, json_data4["Results"]["series"][series4]["seriesID"]] = json_data4["Results"]["series"][series4]["data"][data_point4]["value"]

In [53]:
for column in layoffs_df.columns[3:]:
    layoffs_df[f"{column}"] = layoffs_df[f"{column}"].astype(float)

layoffs_df.rename(columns={"LNS13000000": "Unemployment level, 16yo and over, thousands",
                           "LNS13023621": "Job losers, 16yo and over, thousands",
                           "LNS13023653": "Job losers on layoff, 16yo and over, thousands",
                           "LNS13025699": "Job losers not on layoff, 16yo and over, thousands",
                           "LNS13023705": "Job leavers (quit), 16yo and over, thousands",
                           "LNS13023557": "Reentrants to labor force, 16yo and over, thousands",
                           "LNS13023569": "New entrants to labor force, 16yo and over, thousands"},
                 inplace=True)

layoffs_df.sort_values(by="Date", ascending=True, inplace=True)

layoffs_df.reset_index(drop=True, inplace=True)

In [54]:
pulled_layoffs_data = layoffs_df

In [55]:
layoffrecessionyears = pulled_layoffs_data['Year'].unique()
layoffmonthnumber = [ ]

for year in layoffrecessionyears:
    layoffmonth = 13
    while (layoffmonth > 1): 
        layoffmonth = layoffmonth -1
        layoffmonthnumber.append(layoffmonth)
        if  layoffmonth == 0:
            break
pulled_layoffs_data['Month #'] = layoffmonthnumber

In [56]:
layoffdates = []

for index, row in pulled_layoffs_data.iterrows():
    layoffdatenumber = str(f"{row['Year']}-{row['Month #']}")
    layoffdates.append(layoffdatenumber)

pulled_layoffs_data['Date'] = layoffdates

In [57]:
pulled_layoffs_data = pulled_layoffs_data.rename(columns={'Unemployment level, 16yo and over, thousands': 'Overall Unemployment',
                                     'Job losers, 16yo and over, thousands': 'Loss of Job Total', 'Job losers on layoff, 16yo and over, thousands': 'Loss of Job: On Layoff',
                                     'Job losers not on layoff, 16yo and over, thousands': 'Loss of Job: Not on Layoff', "Job leavers (quit), 16yo and over, thousands": "Number of Persons Quitting",
                                     'Reentrants to labor force, 16yo and over, thousands': 'Reentrants to Labor Force', 'New entrants to labor force, 16yo and over, thousands': 'New Entrants to Labor Force'})

In [58]:
pulled_layoffs_data = pulled_layoffs_data[['Year', 'Month #', 'Date', 'Overall Unemployment', 'Loss of Job Total', 'Loss of Job: On Layoff', 'Loss of Job: Not on Layoff', 
                      'Number of Persons Quitting', 'Reentrants to Labor Force', 'New Entrants to Labor Force']]
pulled_layoffs_data['Year'] = pulled_layoffs_data['Year'].astype(int)
recession_layoffs_data = pulled_layoffs_data[pulled_layoffs_data['Year']<=2011]

In [60]:
recession_layoffs_data.to_csv("Combined_Ouput_File/recession_layoffs_data.csv")

In [61]:
newworkforce = pulled_layoffs_data[['Year', 'Month #', 'Date', 'Overall Unemployment', 'Reentrants to Labor Force', 'New Entrants to Labor Force']]
newworkforce = newworkforce.reindex(index=newworkforce.index[::-1])

newworkforce = newworkforce.reset_index()
del newworkforce['index']
newworkforce['Overall Unemployment'] = newworkforce['Overall Unemployment'].astype(float)

In [62]:
changewf_df_data = newworkforce[['Overall Unemployment', 'Reentrants to Labor Force', 'New Entrants to Labor Force']]
changewf_df_date = newworkforce['Date']
changewf_norm = (changewf_df_data - changewf_df_data.mean()) / (changewf_df_data.max() - changewf_df_data.min())
changewf_norm['Date'] = changewf_df_date
changewf_norm = changewf_norm[['Date', 'Overall Unemployment', 'Reentrants to Labor Force', 'New Entrants to Labor Force']]

In [63]:
changewf_norm.to_csv("Combined_Ouput_File/work_force_adjusted.csv")

In [115]:
layoffsInd_df.set_index(["Years", "Periods","Months","LNS14000000","LNS14000001","LNS14000002","LNS14000003","LNS14000006",
                       "LNS14032183","LNS14000009","LNS14027659","LNS14027660","LNS14027689","LNS14027662","LNS14024887",
                       "LNS14000089","LNS14000091","LNS14000093","LNS14024230"])

Empty DataFrame
Columns: []
Index: [(2018, M12, December, 3.9, 3.9, 3.8, 3.4, 6.6, 3.3, 4.4, 5.8, 3.8, 3.3, 2.2, 8.7, 3.9, 2.8, 2.9, 2.9), (2018, M11, November, 3.7, 3.6, 3.8, 3.4, 6.1, 2.8, 4.5, 5.6, 3.5, 3.1, 2.2, 8.2, 3.7, 2.9, 2.7, 2.8), (2018, M10, October, 3.8, 3.8, 3.8, 3.3, 6.3, 3.1, 4.4, 5.9, 4.0, 3.1, 2.0, 8.4, 3.7, 3.0, 2.8, 2.8), (2018, M09, September, 3.7, 3.8, 3.7, 3.3, 6.2, 3.5, 4.6, 5.7, 3.8, 3.2, 2.0, 8.6, 3.6, 3.0, 2.6, 2.8), (2018, M08, August, 3.8, 3.8, 3.8, 3.4, 6.3, 3.0, 4.7, 5.7, 3.9, 3.5, 2.0, 8.5, 4.1, 2.8, 2.5, 3.0), (2018, M07, July, 3.8, 3.8, 3.9, 3.3, 6.6, 3.1, 4.4, 5.2, 4.1, 3.2, 2.2, 8.6, 3.5, 3.0, 2.9, 3.1), (2018, M06, June, 4.0, 4.1, 3.9, 3.5, 6.5, 3.2, 4.5, 5.5, 4.1, 3.3, 2.3, 8.9, 3.9, 3.1, 3.0, 3.1), (2018, M05, May, 3.8, 4.0, 3.6, 3.5, 5.9, 2.2, 4.9, 5.5, 3.9, 3.3, 2.0, 8.6, 3.9, 2.9, 2.7, 2.8), (2018, M04, April, 4.0, 4.1, 3.8, 3.6, 6.4, 2.8, 4.8, 5.8, 4.3, 3.4, 2.1, 8.5, 4.3, 3.0, 2.8, 3.0), (2018, M03, March, 4.0, 4.1, 4.0, 3.6, 6.8, 3.1, 5.0, 5.5, 4.3, 3.5, 2.2, 8.5, 4.1, 3.2, 2.9, 3.2), (2018, M02, February, 4.1, 4.1, 4.1, 3.7, 6.7, 2.9, 4.9, 5.7, 4.4, 3.5, 2.2, 8.9, 4.2, 3.1, 2.9, 3.2), (2018, M01, January, 4.1, 4.2, 4.0, 3.5, 7.5, 3.0, 5.0, 5.4, 4.4, 3.4, 2.1, 9.0, 4.3, 3.1, 3.0, 3.0), (2017, M12, December, 4.1, 4.1, 4.1, 3.7, 6.7, 2.5, 5.0, 6.2, 4.2, 3.6, 2.2, 8.9, 4.4, 3.0, 2.7, 3.3), (2017, M11, November, 4.2, 4.2, 4.1, 3.7, 7.4, 3.0, 4.8, 5.2, 4.4, 3.6, 2.1, 9.8, 4.3, 3.1, 2.8, 3.1), (2017, M10, October, 4.1, 4.2, 4.0, 3.5, 7.4, 3.0, 4.9, 5.9, 4.2, 3.7, 2.1, 9.1, 4.4, 3.0, 2.8, 3.1), (2017, M09, September, 4.2, 4.3, 4.2, 3.7, 7.2, 3.6, 5.1, 6.7, 4.4, 3.6, 2.3, 9.2, 4.5, 3.2, 3.1, 3.2), (2017, M08, August, 4.4, 4.5, 4.3, 3.8, 7.7, 3.9, 5.2, 6.1, 5.1, 3.7, 2.4, 9.1, 4.8, 3.3, 3.4, 3.2), (2017, M07, July, 4.3, 4.3, 4.2, 3.7, 7.4, 3.8, 5.1, 7.1, 4.5, 3.7, 2.3, 8.9, 4.6, 3.5, 3.1, 3.1), (2017, M06, June, 4.3, 4.4, 4.3, 3.8, 7.1, 3.6, 4.9, 6.5, 4.6, 3.8, 2.3, 9.1, 4.4, 3.4, 3.5, 3.1), (2017, M05, May, 4.4, 4.3, 4.5, 3.8, 7.7, 3.7, 5.2, 6.3, 4.8, 4.1, 2.3, 8.7, 4.9, 3.5, 3.3, 3.1), (2017, M04, April, 4.4, 4.4, 4.5, 3.9, 7.9, 3.3, 5.1, 6.4, 4.6, 3.7, 2.5, 9.5, 4.4, 3.6, 3.5, 3.2), (2017, M03, March, 4.4, 4.6, 4.3, 3.9, 7.9, 3.3, 5.0, 6.6, 4.9, 3.7, 2.4, 9.2, 4.5, 3.8, 3.2, 3.3), (2017, M02, February, 4.6, 4.7, 4.6, 4.0, 7.9, 3.4, 5.5, 7.7, 4.9, 4.0, 2.4, 9.7, 4.7, 4.1, 3.2, 3.4), (2017, M01, January, 4.7, 4.7, 4.7, 4.2, 7.5, 3.7, 5.8, 7.4, 5.2, 3.8, 2.5, 9.8, 4.9, 3.9, 3.3, 3.5), (2016, M12, December, 4.7, 4.8, 4.6, 4.2, 7.9, 2.7, 5.9, 7.5, 5.1, 3.8, 2.5, 9.8, 4.7, 4.0, 3.4, 3.5), (2016, M11, November, 4.7, 4.8, 4.6, 4.2, 8.1, 3.1, 5.8, 7.8, 5.0, 3.9, 2.4, 10.0, 4.8, 3.6, 3.6, 3.5), (2016, M10, October, 4.9, 5.0, 4.7, 4.4, 8.4, 3.4, 5.8, 7.4, 5.4, 3.9, 2.6, 10.4, 5.1, 3.9, 3.5, 3.7), (2016, M09, September, 5.0, 5.1, 4.9, 4.4, 8.5, 3.8, 6.4, 8.5, 5.3, 4.2, 2.5, 10.5, 5.3, 4.2, 3.6, 3.6), (2016, M08, August, 4.9, 5.0, 4.8, 4.3, 8.0, 4.1, 5.6, 7.4, 5.0, 4.2, 2.6, 10.4, 5.0, 4.0, 3.5, 3.5), (2016, M07, July, 4.8, 5.0, 4.6, 4.2, 8.4, 3.8, 5.5, 6.5, 5.1, 4.2, 2.5, 10.7, 5.1, 3.5, 3.5, 3.7), (2016, M06, June, 4.9, 5.0, 4.8, 4.3, 8.8, 3.5, 5.9, 7.6, 5.1, 4.2, 2.5, 10.6, 5.2, 3.8, 3.4, 3.5), (2016, M05, May, 4.8, 4.9, 4.8, 4.2, 8.2, 4.2, 5.6, 7.5, 5.1, 3.9, 2.5, 10.5, 5.1, 3.6, 3.4, 3.4), (2016, M04, April, 5.0, 5.0, 5.0, 4.4, 8.8, 3.8, 6.1, 7.6, 5.5, 4.2, 2.4, 11.0, 5.2, 4.0, 3.6, 3.7), (2016, M03, March, 5.0, 5.0, 5.0, 4.3, 8.9, 3.9, 5.5, 7.3, 5.3, 4.1, 2.6, 10.8, 5.2, 3.8, 3.6, 3.9), (2016, M02, February, 4.9, 4.9, 4.8, 4.3, 8.5, 3.8, 5.4, 7.0, 5.2, 4.2, 2.5, 10.4, 5.0, 3.7, 3.6, 3.8), (2016, M01, January, 4.9, 4.9, 4.9, 4.2, 8.7, 3.6, 5.8, 7.1, 5.2, 4.2, 2.5, 10.0, 5.1, 3.9, 3.6, 3.7), (2015, M12, December, 5.0, 5.1, 4.9, 4.4, 8.5, 4.1, 6.2, 6.4, 5.6, 4.1, 2.5, 11.1, 5.3, 4.0, 3.7, 3.2), (2015, M11, November, 5.1, 5.2, 5.0, 4.4, 9.4, 3.9, 6.4, 6.8, 5.4, 4.4, 2.5, 11.2, 5.5, 4.0, 3.4, 3.7), (2015, M10, October, 5.0, 5.1, 5.0, 4.4, 9.0, 3.5, 6.3, 7.6, 5.2, 4.4, 2.5, 11.0, 5.3, 4.1, 3.7, 3.5), (2015, M09, September, 5.0, 5.1, 5.0, 4.4, 9.3, 3.5, 6.2, 7.9, 5.3, 4.3, 2.5, 11.2, 5.1, 4.0, 3.4, 3.8), (2015, M08, August, 5.1, 5.1, 5.0, 4.4, 9.4, 3.4, 6.6, 7.9, 5.5, 4.3, 2.4, 11.1, 5.1, 3.8, 3.7, 3.8), (2015, M07, July, 5.2, 5.2, 5.2, 4.5, 9.1, 3.9, 6.9, 8.3, 5.5, 4.3, 2.5, 11.5, 5.5, 4.1, 3.7, 3.7), (2015, M06, June, 5.3, 5.3, 5.1, 4.6, 9.7, 3.9, 6.7, 8.2, 5.4, 4.2, 2.5, 11.9, 5.6, 4.0, 3.4, 3.7), (2015, M05, May, 5.6, 5.7, 5.5, 4.8, 10.3, 4.1, 6.8, 8.7, 5.8, 4.4, 2.8, 12.3, 5.8, 4.5, 3.9, 3.8), (2015, M04, April, 5.4, 5.5, 5.4, 4.7, 9.7, 4.4, 6.8, 8.4, 5.5, 4.7, 2.7, 11.8, 5.8, 4.3, 3.9, 4.0), (2015, M03, March, 5.4, 5.6, 5.3, 4.8, 9.9, 3.2, 6.8, 8.6, 5.3, 4.8, 2.4, 12.5, 5.7, 4.1, 3.7, 3.9), (2015, M02, February, 5.5, 5.6, 5.3, 4.7, 10.1, 4.0, 6.8, 8.2, 5.4, 5.0, 2.7, 11.8, 5.4, 4.4, 3.9, 4.2), (2015, M01, January, 5.7, 5.8, 5.5, 4.9, 10.3, 4.0, 6.7, 8.3, 5.4, 5.2, 2.8, 12.0, 5.9, 4.4, 4.2, 4.1), (2014, M12, December, 5.6, 5.7, 5.4, 4.7, 10.6, 4.4, 6.4, 8.6, 5.3, 5.0, 2.8, 12.2, 5.8, 4.3, 4.0, 3.9), (2014, M11, November, 5.8, 5.9, 5.8, 5.0, 10.9, 4.8, 6.6, 8.6, 5.7, 4.9, 3.2, 12.5, 6.0, 4.4, 4.2, 4.5), (2014, M10, October, 5.7, 5.6, 5.9, 4.9, 10.6, 5.1, 6.8, 8.1, 5.7, 4.9, 3.0, 12.6, 6.1, 4.4, 4.0, 4.1), (2014, M09, September, 5.9, 5.9, 6.0, 5.1, 11.0, 4.4, 6.8, 8.5, 5.4, 5.4, 2.9, 13.8, 6.3, 4.4, 4.1, 3.9), (2014, M08, August, 6.1, 6.3, 6.0, 5.3, 11.4, 4.5, 7.4, 9.2, 6.1, 5.3, 3.2, 13.2, 6.8, 4.8, 4.1, 4.5), (2014, M07, July, 6.2, 6.2, 6.1, 5.3, 11.6, 4.2, 7.7, 9.5, 6.1, 5.3, 3.1, 13.5, 6.5, 4.8, 4.1, 4.5), (2014, M06, June, 6.1, 6.3, 5.8, 5.3, 11.0, 4.7, 7.8, 9.2, 5.9, 5.2, 3.3, 13.1, 6.5, 4.7, 4.2, 4.5), (2014, M05, May, 6.3, 6.4, 6.2, 5.4, 11.4, 5.7, 7.7, 9.2, 6.5, 5.5, 3.2, 13.3, 6.6, 5.0, 4.5, 4.6), (2014, M04, April, 6.2, 6.4, 6.1, 5.3, 11.6, 5.9, 7.2, 8.7, 6.2, 5.7, 3.3, 13.0, 6.7, 4.9, 4.6, 4.7), (2014, M03, March, 6.7, 6.7, 6.6, 5.8, 12.1, 5.5, 7.9, 9.4, 6.3, 6.0, 3.4, 14.6, 6.9, 5.2, 4.9, 4.7), (2014, M02, February, 6.7, 6.9, 6.4, 5.8, 11.8, 5.9, 8.2, 9.8, 6.4, 6.0, 3.4, 14.5, 7.1, 5.0, 5.1, 4.5), (2014, M01, January, 6.6, 6.8, 6.3, 5.7, 12.1, 4.7, 8.3, 9.4, 6.5, 5.9, 3.3, 14.1, 6.8, 5.0, 5.0, 4.5), (2013, M12, December, 6.7, 6.8, 6.6, 5.9, 11.9, 4.3, 8.3, 9.8, 7.0, 6.2, 3.3, 13.4, 6.9, 5.4, 5.0, 5.1), (2013, M11, November, 6.9, 7.2, 6.7, 6.1, 12.3, 5.2, 8.7, 10.7, 7.2, 6.4, 3.4, 14.1, 7.3, 5.7, 5.5, 4.9), (2013, M10, October, 7.2, 7.5, 6.8, 6.3, 12.8, 5.4, 9.1, 10.9, 7.2, 6.4, 3.7, 14.8, 7.1, 5.7, 5.8, 5.5), (2013, M09, September, 7.2, 7.7, 6.7, 6.3, 13.0, 5.4, 8.8, 10.5, 7.6, 6.1, 3.7, 15.1, 7.4, 5.6, 5.6, 5.2), (2013, M08, August, 7.2, 7.7, 6.7, 6.4, 12.8, 5.1, 9.2, 11.1, 7.4, 6.1, 3.4, 15.7, 7.7, 5.6, 5.4, 5.0), (2013, M07, July, 7.3, 7.7, 6.8, 6.5, 12.6, 5.3, 9.4, 10.8, 7.5, 6.1, 3.8, 15.4, 7.5, 5.9, 5.6, 5.0), (2013, M06, June, 7.5, 7.7, 7.3, 6.6, 14.2, 4.7, 9.1, 10.7, 7.7, 6.5, 3.8, 16.0, 7.6, 5.9, 5.8, 5.4), (2013, M05, May, 7.5, 7.9, 7.1, 6.7, 13.4, 4.5, 9.0, 11.0, 7.3, 6.5, 3.9, 16.3, 7.2, 6.0, 5.9, 5.3), (2013, M04, April, 7.6, 7.8, 7.3, 6.7, 13.3, 5.3, 9.0, 11.6, 7.5, 6.4, 3.9, 16.3, 7.5, 5.9, 5.9, 5.5), (2013, M03, March, 7.5, 7.6, 7.5, 6.7, 13.0, 5.1, 9.3, 11.1, 7.7, 6.3, 3.8, 16.1, 7.5, 6.1, 5.7, 5.5), (2013, M02, February, 7.7, 7.8, 7.6, 6.8, 13.8, 6.0, 9.7, 11.3, 7.9, 6.5, 3.9, 16.3, 7.7, 6.2, 5.6, 5.7), (2013, M01, January, 8.0, 8.2, 7.8, 7.1, 13.7, 6.4, 9.7, 12.0, 8.1, 6.9, 3.8, 16.8, 7.7, 6.5, 6.0, 6.0), (2012, M12, December, 7.9, 7.9, 7.9, 6.9, 14.0, 6.6, 9.6, 11.8, 8.0, 6.9, 4.0, 16.5, 7.8, 6.6, 5.8, 5.9), (2012, M11, November, 7.7, 7.9, 7.6, 6.8, 13.3, 6.3, 9.9, 12.0, 8.0, 6.5, 3.9, 15.9, 7.7, 6.2, 6.0, 5.8), (2012, M10, October, 7.8, 7.9, 7.6, 6.9, 14.1, 4.9, 10.0, 12.1, 8.3, 6.9, 3.7, 16.0, 8.1, 6.2, 6.0, 5.9), (2012, M09, September, 7.8, 8.0, 7.6, 7.0, 13.6, 4.9, 9.7, 11.7, 8.5, 6.6, 4.0, 15.5, 8.0, 6.3, 6.0, 5.9), (2012, M08, August, 8.1, 8.3, 7.8, 7.2, 13.8, 5.9, 10.1, 11.8, 8.6, 6.7, 4.1, 16.7, 8.2, 6.6, 6.3, 5.8), (2012, M07, July, 8.2, 8.3, 8.0, 7.3, 14.2, 5.9, 10.2, 12.4, 8.5, 7.2, 4.1, 16.3, 8.1, 6.7, 6.5, 6.2), (2012, M06, June, 8.2, 8.4, 7.9, 7.3, 14.5, 6.1, 10.9, 12.6, 8.6, 7.3, 4.0, 16.2, 8.2, 7.0, 6.4, 6.2), (2012, M05, May, 8.2, 8.4, 7.9, 7.4, 13.5, 5.5, 10.9, 12.9, 8.3, 7.7, 3.9, 16.1, 8.2, 6.7, 6.3, 6.5), (2012, M04, April, 8.2, 8.3, 8.0, 7.4, 13.3, 5.4, 10.3, 12.5, 8.0, 7.6, 4.0, 16.6, 8.2, 6.6, 6.2, 6.3), (2012, M03, March, 8.2, 8.4, 8.0, 7.3, 14.0, 6.4, 10.6, 12.8, 8.1, 7.5, 4.1, 16.2, 8.7, 6.4, 6.3, 6.2), (2012, M02, February, 8.3, 8.4, 8.1, 7.4, 14.0, 6.2, 10.9, 13.1, 8.3, 7.2, 4.2, 16.5, 8.6, 6.8, 6.5, 5.8), (2012, M01, January, 8.3, 8.4, 8.2, 7.4, 13.6, 6.7, 10.7, 13.0, 8.5, 7.1, 4.3, 16.1, 9.0, 6.8, 6.4, 5.9), (2011, M12, December, 8.5, 8.7, 8.3, 7.5, 15.4, 6.8, 11.1, 13.7, 8.7, 7.6, 4.1, 16.7, 9.3, 6.8, 6.5, 6.2), (2011, M11, November, 8.6, 8.9, 8.3, 7.7, 15.6, 6.4, 11.2, 12.8, 8.8, 7.7, 4.4, 17.0, 9.1, 7.0, 6.6, 6.3), (2011, M10, October, 8.8, 9.2, 8.4, 7.9, 14.6, 7.4, 11.3, 13.5, 9.4, 8.1, 4.3, 16.7, 9.5, 7.2, 6.9, 7.0), (2011, M09, September, 9.0, 9.3, 8.7, 7.9, 15.9, 8.0, 11.2, 14.3, 9.4, 8.5, 4.2, 17.3, 9.5, 7.5, 7.1, 6.6), (2011, M08, August, 9.0, 9.4, 8.5, 7.9, 16.4, 7.2, 11.2, 14.1, 9.3, 8.3, 4.2, 17.4, 9.4, 7.7, 7.0, 6.6), (2011, M07, July, 9.0, 9.5, 8.4, 8.0, 15.9, 7.4, 11.2, 14.5, 9.1, 8.3, 4.2, 17.3, 9.6, 7.0, 7.1, 6.8), (2011, M06, June, 9.1, 9.6, 8.5, 8.1, 16.2, 6.5, 11.5, 14.4, 10.0, 8.3, 4.3, 17.1, 9.6, 7.7, 7.3, 6.9), (2011, M05, May, 9.0, 9.5, 8.5, 7.9, 16.3, 7.2, 11.6, 14.5, 9.6, 7.8, 4.5, 17.3, 9.5, 7.5, 7.2, 6.7), (2011, M04, April, 9.1, 9.6, 8.5, 8.1, 16.5, 6.5, 11.9, 14.7, 9.9, 7.5, 4.5, 17.6, 9.8, 7.4, 7.2, 6.5), (2011, M03, March, 9.0, 9.5, 8.4, 8.0, 15.8, 7.3, 11.6, 14.1, 9.7, 7.5, 4.4, 17.6, 9.3, 7.2, 7.2, 6.5), (2011, M02, February, 9.0, 9.5, 8.5, 8.1, 15.5, 6.7, 11.8, 14.0, 9.7, 7.9, 4.3, 17.7, 9.5, 7.4, 7.1, 6.5), (2011, M01, January, 9.1, 9.7, 8.5, 8.1, 15.8, 6.8, 12.3, 14.3, 9.5, 8.1, 4.3, 18.1, 9.3, 7.4, 7.2, 6.7), (2010, M12, December, 9.3, 10.0, 8.5, 8.5, 15.5, 7.2, 12.9, 15.0, 9.8, 8.1, 4.8, 17.9, 9.9, 7.7, 7.5, 6.8), (2010, M11, November, 9.8, 10.5, 9.0, 8.9, 16.2, 7.5, 12.9, 15.4, 10.0, 8.6, 5.0, 18.5, 10.4, 7.8, 8.1, 7.2), (2010, M10, October, 9.4, 10.1, 8.7, 8.6, 15.6, 7.2, 12.3, 15.0, 9.8, 8.2, 4.6, 18.7, 9.6, 7.8, 7.6, 7.1), (2010, M09, September, 9.5, 10.2, 8.6, 8.6, 16.0, 6.6, 12.3, 15.6, 9.7, 8.9, 4.5, 17.9, 9.8, 8.3, 7.5, 7.1), ...]

[156 rows x 0 columns]

In [116]:
# Rename column labels

layoffsInd_df.rename(columns={
                           "LNS14000000": "Unemployment Rate for 16yo and over",
                           "LNS14000001": "Unemployment Rate for Men 16yo and over",
                           "LNS14000002": "Unemployment Rate for Women 16yo and over",
                           "LNS14000003": "Unemployment Rate for White people 16yo and over",
                           "LNS14000006": "Unemployment Rate for African Americans 16yo and over",
                           "LNS14032183": "Unemployment Rate for Asian people 16yo and over",
                           "LNS14000009": "Unemployment Rate for Hispanic people 16yo and over",
                           "LNS14027659": "Unemployment Rate for 25yo and older with less than High School Diploma",
                           "LNS14027660": "Unemployment Rate for 25yo and older with High School Degree",
                           "LNS14027689": "Unemployment Rate for 25yo and older with some college",
                           "LNS14027662": "Unemployment Rate for 25yo and older with Bachelor's degree or higher",
                           "LNS14024887": "Unemployment Rate for 16-24yo",
                           "LNS14000089": "Unemployment Rate for 25-34yo",
                           "LNS14000091": "Unemployment Rate for 35-44yo",
                           "LNS14000093": "Unemployment Rate for 45-54yo",
                            "LNS14024230": "Unemployment Rate for 55yo and over"
                          },
                      inplace=True)
layoffsInd_df['Unemployment Rate for 16yo and over'] = pd.to_numeric(layoffsInd_df['Unemployment Rate for 16yo and over'])

grouped_layoffs = layoffsInd_df.groupby('Years')['Unemployment Rate for 16yo and over'].mean()
grouped_layoffs = grouped_layoffs.reset_index()
grouped_layoffs.head(13)

   Years  Unemployment Rate for 16yo and over
0   2006                             4.608333
1   2007                             4.616667
2   2008                             5.800000
3   2009                             9.283333
4   2010                             9.608333
5   2011                             8.933333
6   2012                             8.075000
7   2013                             7.358333
8   2014                             6.158333
9   2015                             5.275000
10  2016                             4.875000
11  2017                             4.341667
12  2018                             3.891667

In [117]:
grouped_layoffs2 = layoffsInd_df.groupby(['Years','Periods','Months'])['Unemployment Rate for 16yo and over'].mean()
grouped_layoffs2 = grouped_layoffs2.reset_index()
#grouped_layoffs2.head(13)

In [127]:
# Output layoff File (CSV)
output_layoffs_file = "Combined_Ouput_File/layoffs.csv"

#city data into a .csv.
grouped_layoffs2.to_csv(output_layoffs_file,index=False)

## Industry BLS pull

In [128]:
#Industy Data Pull
url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
headers = {"content-type": "application/json"}

target_series = ["CES0000000001",
                 "CES0500000001", 
                 "CES0600000001", 
                 "CES0700000001", 
                 "CES0800000001", 
                 "CES1000000001", 
                 "CES2000000001", 
                 "CES3000000001", 
                 "CES3100000001", 
                 "CES3200000001", 
                 "CES4000000001", 
                 "CES4142000001", 
                 "CES4200000001", 
                 "CES4300000001", 
                 "CES4422000001", 
                 "CES5000000001", 
                 "CES5500000001", 
                 "CES6000000001", 
                 "CES6500000001", 
                 "CES7000000001", 
                 "CES8000000001", 
                 "CES9000000001"
                ]
#start_year = "2008"
#end_year = "2020"

parameters = json.dumps({"seriesid": target_series,
             "startyear": start_year,
             "endyear": end_year,
             "registrationkey": bls_api_key})

p = requests.post(url, data=parameters, headers=headers)

json_data4 = json.loads(p.text)

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 1533,
 'message': [],
 'Results': {'series': [{'seriesID': 'CES0000000001',
    'data': [{'year': '2018',
      'period': 'M12',
      'periodName': 'December',
      'value': '149865',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M11',
      'periodName': 'November',
      'value': '149683',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M10',
      'periodName': 'October',
      'value': '149549',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M09',
      'periodName': 'September',
      'value': '149348',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M08',
      'periodName': 'August',
      'value': '149268',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M07',
      'periodName': 'July',
      'value': '149024',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M06',
      'periodName': 'June',
      'value': '148888',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M05',
      'periodName': 'May',
      'value': '148669',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M04',
      'periodName': 'April',
      'value': '148391',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M03',
      'periodName': 'March',
      'value': '148254',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M02',
      'periodName': 'February',
      'value': '148078',
      'footnotes': [{}]},
     {'year': '2018',
      'period': 'M01',
      'periodName': 'January',
      'value': '147672',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M12',
      'periodName': 'December',
      'value': '147551',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M11',
      'periodName': 'November',
      'value': '147421',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M10',
      'periodName': 'October',
      'value': '147196',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M09',
      'periodName': 'September',
      'value': '146929',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M08',
      'periodName': 'August',
      'value': '146911',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M07',
      'periodName': 'July',
      'value': '146727',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M06',
      'periodName': 'June',
      'value': '146512',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M05',
      'periodName': 'May',
      'value': '146296',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M04',
      'periodName': 'April',
      'value': '146141',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M03',
      'periodName': 'March',
      'value': '145944',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M02',
      'periodName': 'February',
      'value': '145815',
      'footnotes': [{}]},
     {'year': '2017',
      'period': 'M01',
      'periodName': 'January',
      'value': '145627',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M12',
      'periodName': 'December',
      'value': '145442',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M11',
      'periodName': 'November',
      'value': '145212',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M10',
      'periodName': 'October',
      'value': '145061',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M09',
      'periodName': 'September',
      'value': '144916',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M08',
      'periodName': 'August',
      'value': '144647',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M07',
      'periodName': 'July',
      'value': '144512',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M06',
      'periodName': 'June',
      'value': '144158',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M05',
      'periodName': 'May',
      'value': '143891',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M04',
      'periodName': 'April',
      'value': '143849',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M03',
      'periodName': 'March',
      'value': '143662',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M02',
      'periodName': 'February',
      'value': '143433',
      'footnotes': [{}]},
     {'year': '2016',
      'period': 'M01',
      'periodName': 'January',
      'value': '143170',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M12',
      'periodName': 'December',
      'value': '143097',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M11',
      'periodName': 'November',
      'value': '142824',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M10',
      'periodName': 'October',
      'value': '142587',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M09',
      'periodName': 'September',
      'value': '142281',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M08',
      'periodName': 'August',
      'value': '142126',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M07',
      'periodName': 'July',
      'value': '142001',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M06',
      'periodName': 'June',
      'value': '141699',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M05',
      'periodName': 'May',
      'value': '141525',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M04',
      'periodName': 'April',
      'value': '141194',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M03',
      'periodName': 'March',
      'value': '140910',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M02',
      'periodName': 'February',
      'value': '140839',
      'footnotes': [{}]},
     {'year': '2015',
      'period': 'M01',
      'periodName': 'January',
      'value': '140568',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M12',
      'periodName': 'December',
      'value': '140377',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M11',
      'periodName': 'November',
      'value': '140109',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M10',
      'periodName': 'October',
      'value': '139818',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M09',
      'periodName': 'September',
      'value': '139566',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M08',
      'periodName': 'August',
      'value': '139257',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M07',
      'periodName': 'July',
      'value': '139069',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M06',
      'periodName': 'June',
      'value': '138837',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M05',
      'periodName': 'May',
      'value': '138511',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M04',
      'periodName': 'April',
      'value': '138293',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M03',
      'periodName': 'March',
      'value': '137968',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M02',
      'periodName': 'February',
      'value': '137714',
      'footnotes': [{}]},
     {'year': '2014',
      'period': 'M01',
      'periodName': 'January',
      'value': '137548',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M12',
      'periodName': 'December',
      'value': '137373',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M11',
      'periodName': 'November',
      'value': '137304',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M10',
      'periodName': 'October',
      'value': '137040',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M09',
      'periodName': 'September',
      'value': '136815',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M08',
      'periodName': 'August',
      'value': '136628',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M07',
      'periodName': 'July',
      'value': '136386',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M06',
      'periodName': 'June',
      'value': '136274',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M05',
      'periodName': 'May',
      'value': '136093',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M04',
      'periodName': 'April',
      'value': '135871',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M03',
      'periodName': 'March',
      'value': '135680',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M02',
      'periodName': 'February',
      'value': '135541',
      'footnotes': [{}]},
     {'year': '2013',
      'period': 'M01',
      'periodName': 'January',
      'value': '135263',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M12',
      'periodName': 'December',
      'value': '135072',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M11',
      'periodName': 'November',
      'value': '134833',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M10',
      'periodName': 'October',
      'value': '134677',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M09',
      'periodName': 'September',
      'value': '134518',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M08',
      'periodName': 'August',
      'value': '134331',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M07',
      'periodName': 'July',
      'value': '134159',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M06',
      'periodName': 'June',
      'value': '134007',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M05',
      'periodName': 'May',
      'value': '133934',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M04',
      'periodName': 'April',
      'value': '133834',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M03',
      'periodName': 'March',
      'value': '133752',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M02',
      'periodName': 'February',
      'value': '133512',
      'footnotes': [{}]},
     {'year': '2012',
      'period': 'M01',
      'periodName': 'January',
      'value': '133250',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M12',
      'periodName': 'December',
      'value': '132896',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M11',
      'periodName': 'November',
      'value': '132694',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M10',
      'periodName': 'October',
      'value': '132562',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M09',
      'periodName': 'September',
      'value': '132358',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M08',
      'periodName': 'August',
      'value': '132125',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M07',
      'periodName': 'July',
      'value': '131999',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M06',
      'periodName': 'June',
      'value': '131939',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M05',
      'periodName': 'May',
      'value': '131703',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M04',
      'periodName': 'April',
      'value': '131602',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M03',
      'periodName': 'March',
      'value': '131288',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M02',
      'periodName': 'February',
      'value': '131053',
      'footnotes': [{}]},
     {'year': '2011',
      'period': 'M01',
      'periodName': 'January',
      'value': '130841',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M12',
      'periodName': 'December',
      'value': '130822',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M11',
      'periodName': 'November',
      'value': '130750',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M10',
      'periodName': 'October',
      'value': '130625',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M09',
      'periodName': 'September',
      'value': '130357',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M08',
      'periodName': 'August',
      'value': '130422',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M07',
      'periodName': 'July',
      'value': '130427',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M06',
      'periodName': 'June',
      'value': '130511',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M05',
      'periodName': 'May',
      'value': '130650',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M04',
      'periodName': 'April',
      'value': '130110',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M03',
      'periodName': 'March',
      'value': '129879',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M02',
      'periodName': 'February',
      'value': '129698',
      'footnotes': [{}]},
     {'year': '2010',
      'period': 'M01',
      'periodName': 'January',
      'value': '129790',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M12',
      'periodName': 'December',
      'value': '129788',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M11',
      'periodName': 'November',
      'value': '130057',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M10',
      'periodName': 'October',
      'value': '130045',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M09',
      'periodName': 'September',
      'value': '130244',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M08',
      'periodName': 'August',
      'value': '130485',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M07',
      'periodName': 'July',
      'value': '130668',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M06',
      'periodName': 'June',
      'value': '131008',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M05',
      'periodName': 'May',
      'value': '131475',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M04',
      'periodName': 'April',
      'value': '131817',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M03',
      'periodName': 'March',
      'value': '132512',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M02',
      'periodName': 'February',
      'value': '133312',
      'footnotes': [{}]},
     {'year': '2009',
      'period': 'M01',
      'periodName': 'January',
      'value': '134055',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M12',
      'periodName': 'December',
      'value': '134839',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M11',
      'periodName': 'November',
      'value': '135545',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M10',
      'periodName': 'October',
      'value': '136272',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M09',
      'periodName': 'September',
      'value': '136753',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M08',
      'periodName': 'August',
      'value': '137213',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M07',
      'periodName': 'July',
      'value': '137491',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M06',
      'periodName': 'June',
      'value': '137687',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M05',
      'periodName': 'May',
      'value': '137858',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M04',
      'periodName': 'April',
      'value': '138035',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M03',
      'periodName': 'March',
      'value': '138275',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M02',
      'periodName': 'February',
      'value': '138324',
      'footnotes': [{}]},
     {'year': '2008',
      'period': 'M01',
      'periodName': 'January',
      'value': '138403',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M12',
      'periodName': 'December',
      'value': '138392',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M11',
      'periodName': 'November',
      'value': '138284',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M10',
      'periodName': 'October',
      'value': '138174',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M09',
      'periodName': 'September',
      'value': '138095',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M08',
      'periodName': 'August',
      'value': '138015',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M07',
      'periodName': 'July',
      'value': '138038',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M06',
      'periodName': 'June',
      'value': '138069',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M05',
      'periodName': 'May',
      'value': '137993',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M04',
      'periodName': 'April',
      'value': '137842',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M03',
      'periodName': 'March',
      'value': '137793',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M02',
      'periodName': 'February',
      'value': '137558',
      'footnotes': [{}]},
     {'year': '2007',
      'period': 'M01',
      'periodName': 'January',
      'value': '137477',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M12',
      'periodName': 'December',
      'value': '137249',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M11',
      'periodName': 'November',
      'value': '137063',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M10',
      'periodName': 'October',
      'value': '136852',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M09',
      'periodName': 'September',
      'value': '136843',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M08',
      'periodName': 'August',
      'value': '136694',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M07',
      'periodName': 'July',
      'value': '136520',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M06',
      'periodName': 'June',
      'value': '136325',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M05',
      'periodName': 'May',
      'value': '136244',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M04',
      'periodName': 'April',
      'value': '136205',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M03',
      'periodName': 'March',
      'value': '136047',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M02',
      'periodName': 'February',
      'value': '135737',
      'footnotes': [{}]},
     {'year': '2006',
      'period': 'M01',
      'periodName': 'January',
      'value': '135429',
      'footnotes': [{}]}]},
   {'seriesID': 'CES0500000001',
    'data': [{'year': '2018',
      'period': 'M12',
      'periodName': 'December',
      'value': '127370',
      'footnotes': [{}]},

In [129]:
years = []
months = []
periods = []

for data_point in np.arange(len(json_data4["Results"]["series"][0]["data"])):
        years.append(json_data4["Results"]["series"][0]["data"][data_point]["year"])
        months.append(json_data4["Results"]["series"][0]["data"][data_point]["periodName"])
        periods.append(json_data4["Results"]["series"][0]["data"][data_point]["period"])

In [130]:
# Create DataFrame with place holders for unemployment categories

industry_df = pd.DataFrame({"Years": years,
                            "Periods": periods,
                           "Months": months,
                           "CES0000000001":"", 
                           "CES0500000001":"",
                           "CES0600000001":"", 
                           "CES0700000001":"",
                           "CES0800000001":"", 
                           "CES1000000001":"",
                           "CES2000000001":"",
                           "CES3000000001":"", 
                           "CES3100000001":"",
                           "CES3200000001":"",
                           "CES4000000001":"", 
                           "CES4142000001":"",
                           "CES4200000001":"",
                           "CES4300000001":"", 
                           "CES4422000001":"",
                           "CES5000000001":"",
                           "CES5500000001":"", 
                           "CES6000000001":"",
                           "CES6500000001":"",
                           "CES7000000001":"", 
                           "CES8000000001":"",
                           "CES9000000001":""
                          })
industry_df.set_index(["Years", "Periods","Months",
                      "CES0000000001",
                      "CES0500000001", 
                      "CES0600000001", 
                      "CES0700000001", 
                      "CES0800000001", 
                      "CES1000000001", 
                      "CES2000000001", 
                      "CES3000000001", 
                      "CES3100000001", 
                      "CES3200000001", 
                      "CES4000000001", 
                      "CES4142000001", 
                      "CES4200000001", 
                      "CES4300000001", 
                      "CES4422000001", 
                      "CES5000000001", 
                      "CES5500000001", 
                      "CES6000000001", 
                      "CES6500000001", 
                      "CES7000000001", 
                      "CES8000000001", 
                      "CES9000000001"
                     ])
#industry_df.head(12)

Empty DataFrame
Columns: []
Index: [(2018, M12, December, , , , , , , , , , , , , , , , , , , , , , ), (2018, M11, November, , , , , , , , , , , , , , , , , , , , , , ), (2018, M10, October, , , , , , , , , , , , , , , , , , , , , , ), (2018, M09, September, , , , , , , , , , , , , , , , , , , , , , ), (2018, M08, August, , , , , , , , , , , , , , , , , , , , , , ), (2018, M07, July, , , , , , , , , , , , , , , , , , , , , , ), (2018, M06, June, , , , , , , , , , , , , , , , , , , , , , ), (2018, M05, May, , , , , , , , , , , , , , , , , , , , , , ), (2018, M04, April, , , , , , , , , , , , , , , , , , , , , , ), (2018, M03, March, , , , , , , , , , , , , , , , , , , , , , ), (2018, M02, February, , , , , , , , , , , , , , , , , , , , , , ), (2018, M01, January, , , , , , , , , , , , , , , , , , , , , , ), (2017, M12, December, , , , , , , , , , , , , , , , , , , , , , ), (2017, M11, November, , , , , , , , , , , , , , , , , , , , , , ), (2017, M10, October, , , , , , , , , , , , , , , , , , , , , , ), (2017, M09, September, , , , , , , , , , , , , , , , , , , , , , ), (2017, M08, August, , , , , , , , , , , , , , , , , , , , , , ), (2017, M07, July, , , , , , , , , , , , , , , , , , , , , , ), (2017, M06, June, , , , , , , , , , , , , , , , , , , , , , ), (2017, M05, May, , , , , , , , , , , , , , , , , , , , , , ), (2017, M04, April, , , , , , , , , , , , , , , , , , , , , , ), (2017, M03, March, , , , , , , , , , , , , , , , , , , , , , ), (2017, M02, February, , , , , , , , , , , , , , , , , , , , , , ), (2017, M01, January, , , , , , , , , , , , , , , , , , , , , , ), (2016, M12, December, , , , , , , , , , , , , , , , , , , , , , ), (2016, M11, November, , , , , , , , , , , , , , , , , , , , , , ), (2016, M10, October, , , , , , , , , , , , , , , , , , , , , , ), (2016, M09, September, , , , , , , , , , , , , , , , , , , , , , ), (2016, M08, August, , , , , , , , , , , , , , , , , , , , , , ), (2016, M07, July, , , , , , , , , , , , , , , , , , , , , , ), (2016, M06, June, , , , , , , , , , , , , , , , , , , , , , ), (2016, M05, May, , , , , , , , , , , , , , , , , , , , , , ), (2016, M04, April, , , , , , , , , , , , , , , , , , , , , , ), (2016, M03, March, , , , , , , , , , , , , , , , , , , , , , ), (2016, M02, February, , , , , , , , , , , , , , , , , , , , , , ), (2016, M01, January, , , , , , , , , , , , , , , , , , , , , , ), (2015, M12, December, , , , , , , , , , , , , , , , , , , , , , ), (2015, M11, November, , , , , , , , , , , , , , , , , , , , , , ), (2015, M10, October, , , , , , , , , , , , , , , , , , , , , , ), (2015, M09, September, , , , , , , , , , , , , , , , , , , , , , ), (2015, M08, August, , , , , , , , , , , , , , , , , , , , , , ), (2015, M07, July, , , , , , , , , , , , , , , , , , , , , , ), (2015, M06, June, , , , , , , , , , , , , , , , , , , , , , ), (2015, M05, May, , , , , , , , , , , , , , , , , , , , , , ), (2015, M04, April, , , , , , , , , , , , , , , , , , , , , , ), (2015, M03, March, , , , , , , , , , , , , , , , , , , , , , ), (2015, M02, February, , , , , , , , , , , , , , , , , , , , , , ), (2015, M01, January, , , , , , , , , , , , , , , , , , , , , , ), (2014, M12, December, , , , , , , , , , , , , , , , , , , , , , ), (2014, M11, November, , , , , , , , , , , , , , , , , , , , , , ), (2014, M10, October, , , , , , , , , , , , , , , , , , , , , , ), (2014, M09, September, , , , , , , , , , , , , , , , , , , , , , ), (2014, M08, August, , , , , , , , , , , , , , , , , , , , , , ), (2014, M07, July, , , , , , , , , , , , , , , , , , , , , , ), (2014, M06, June, , , , , , , , , , , , , , , , , , , , , , ), (2014, M05, May, , , , , , , , , , , , , , , , , , , , , , ), (2014, M04, April, , , , , , , , , , , , , , , , , , , , , , ), (2014, M03, March, , , , , , , , , , , , , , , , , , , , , , ), (2014, M02, February, , , , , , , , , , , , , , , , , , , , , , ), (2014, M01, January, , , , , , , , , , , , , , , , , , , , , , ), (2013, M12, December, , , , , , , , , , , , , , , , , , , , , , ), (2013, M11, November, , , , , , , , , , , , , , , , , , , , , , ), (2013, M10, October, , , , , , , , , , , , , , , , , , , , , , ), (2013, M09, September, , , , , , , , , , , , , , , , , , , , , , ), (2013, M08, August, , , , , , , , , , , , , , , , , , , , , , ), (2013, M07, July, , , , , , , , , , , , , , , , , , , , , , ), (2013, M06, June, , , , , , , , , , , , , , , , , , , , , , ), (2013, M05, May, , , , , , , , , , , , , , , , , , , , , , ), (2013, M04, April, , , , , , , , , , , , , , , , , , , , , , ), (2013, M03, March, , , , , , , , , , , , , , , , , , , , , , ), (2013, M02, February, , , , , , , , , , , , , , , , , , , , , , ), (2013, M01, January, , , , , , , , , , , , , , , , , , , , , , ), (2012, M12, December, , , , , , , , , , , , , , , , , , , , , , ), (2012, M11, November, , , , , , , , , , , , , , , , , , , , , , ), (2012, M10, October, , , , , , , , , , , , , , , , , , , , , , ), (2012, M09, September, , , , , , , , , , , , , , , , , , , , , , ), (2012, M08, August, , , , , , , , , , , , , , , , , , , , , , ), (2012, M07, July, , , , , , , , , , , , , , , , , , , , , , ), (2012, M06, June, , , , , , , , , , , , , , , , , , , , , , ), (2012, M05, May, , , , , , , , , , , , , , , , , , , , , , ), (2012, M04, April, , , , , , , , , , , , , , , , , , , , , , ), (2012, M03, March, , , , , , , , , , , , , , , , , , , , , , ), (2012, M02, February, , , , , , , , , , , , , , , , , , , , , , ), (2012, M01, January, , , , , , , , , , , , , , , , , , , , , , ), (2011, M12, December, , , , , , , , , , , , , , , , , , , , , , ), (2011, M11, November, , , , , , , , , , , , , , , , , , , , , , ), (2011, M10, October, , , , , , , , , , , , , , , , , , , , , , ), (2011, M09, September, , , , , , , , , , , , , , , , , , , , , , ), (2011, M08, August, , , , , , , , , , , , , , , , , , , , , , ), (2011, M07, July, , , , , , , , , , , , , , , , , , , , , , ), (2011, M06, June, , , , , , , , , , , , , , , , , , , , , , ), (2011, M05, May, , , , , , , , , , , , , , , , , , , , , , ), (2011, M04, April, , , , , , , , , , , , , , , , , , , , , , ), (2011, M03, March, , , , , , , , , , , , , , , , , , , , , , ), (2011, M02, February, , , , , , , , , , , , , , , , , , , , , , ), (2011, M01, January, , , , , , , , , , , , , , , , , , , , , , ), (2010, M12, December, , , , , , , , , , , , , , , , , , , , , , ), (2010, M11, November, , , , , , , , , , , , , , , , , , , , , , ), (2010, M10, October, , , , , , , , , , , , , , , , , , , , , , ), (2010, M09, September, , , , , , , , , , , , , , , , , , , , , , ), ...]

[156 rows x 0 columns]

In [131]:
# Fills in values for Idustry data

for series4 in np.arange(len(json_data4["Results"]["series"])):
    for data_point4 in np.arange(len(json_data4["Results"]["series"][series4]["data"])):
        industry_df.loc[data_point4, json_data4["Results"]["series"][series4]["seriesID"]] =\
        json_data4["Results"]["series"][series4]["data"][data_point4]["value"]
        
#industry_df.head(10)

In [132]:
# Rename columns to make more informative
industry_df.rename(columns={"CES0000000001":"Total Non-Farm",
                           "CES0500000001":"Total Private",
                           "CES0600000001":"Goods Production", 
                           "CES0700000001":"Service Production",
                           "CES0800000001":"Private Service Production", 
                           "CES1000000001":"Mining and Lodging",
                           "CES2000000001":"Construction",
                           "CES3000000001":"Manufacturing", 
                           "CES3100000001":"Durable Goods",
                           "CES3200000001":"NonDurable Good",
                           "CES4000000001":"Trade, Transportation and Utilities", 
                           "CES4142000001":"WholeSale Trade",
                           "CES4200000001":"Retail Trade",
                           "CES4300000001":"Transportation and Warehousing", 
                           "CES4422000001":"Utilities",
                           "CES5000000001":"Information",
                           "CES5500000001":"Financial Activities", 
                           "CES6000000001":"Professional and Business Services",
                           "CES6500000001":"Education and Health Services",
                           "CES7000000001":"Leisure and Hospitality", 
                           "CES8000000001":"Other Services",
                           "CES9000000001":"Government"},
                 inplace=True)

industry_df['Total Non-Farm'] = pd.to_numeric(industry_df['Total Non-Farm'])
industry_df['Total Private'] = pd.to_numeric(industry_df['Total Private'])
industry_df['Goods Production'] = pd.to_numeric(industry_df['Goods Production'])
industry_df['Service Production'] = pd.to_numeric(industry_df['Service Production'])
industry_df['Private Service Production'] = pd.to_numeric(industry_df['Private Service Production'])
industry_df['Mining and Lodging'] = pd.to_numeric(industry_df['Mining and Lodging'])
industry_df['Construction'] = pd.to_numeric(industry_df['Construction'])
industry_df['Manufacturing'] = pd.to_numeric(industry_df['Manufacturing'])
industry_df['Durable Goods'] = pd.to_numeric(industry_df['Durable Goods'])
industry_df['NonDurable Good'] = pd.to_numeric(industry_df['NonDurable Good'])
industry_df['Trade, Transportation and Utilities'] = pd.to_numeric(industry_df['Trade, Transportation and Utilities'])
industry_df['WholeSale Trade'] = pd.to_numeric(industry_df['WholeSale Trade'])
industry_df['Retail Trade'] = pd.to_numeric(industry_df['Retail Trade'])
industry_df['Transportation and Warehousing'] = pd.to_numeric(industry_df['Transportation and Warehousing'])
industry_df['Utilities'] = pd.to_numeric(industry_df['Utilities'])
industry_df['Information'] = pd.to_numeric(industry_df['Information'])
industry_df['Financial Activities'] = pd.to_numeric(industry_df['Financial Activities'])
industry_df['Professional and Business Services'] = pd.to_numeric(industry_df['Professional and Business Services'])
industry_df['Education and Health Services'] = pd.to_numeric(industry_df['Education and Health Services'])
industry_df['Leisure and Hospitality'] = pd.to_numeric(industry_df['Leisure and Hospitality'])
industry_df['Other Services'] = pd.to_numeric(industry_df['Other Services'])
industry_df['Government'] = pd.to_numeric(industry_df['Government'])
industry_df['Unemployment Rate for 16yo and over'] = grouped_layoffs2['Unemployment Rate for 16yo and over']

In [133]:
grouped_industry = industry_df.groupby(['Years']).mean()
grouped_industry = grouped_industry.reset_index()

In [134]:
# Output industry File (CSV)
output_industry_file = "Combined_Ouput_File/industry.csv"

#city data into a .csv.
grouped_industry.to_csv(output_industry_file,index=False)

In [135]:
unemployment_df.to_csv("Combined_Ouput_File/unemployment_data.csv",index=False)

# Gender Statistics

In [136]:
#Create gender df
unemployment= pd.read_csv("Combined_Ouput_File/unemployment_data.csv")
gender_unemployment_df= unemployment_df[["Year","Unemployment Rate, Men, 16yo and over",
                                 "Unemployment Rate, Women, 16yo and over",
                                 "Unemployment Rate, 16yo and over"
                               ]]
#Variables to convert into int/float

years= gender_unemployment_df["Year"].astype(int)
male_data= gender_unemployment_df["Unemployment Rate, Men, 16yo and over"].astype(float)
female_data= gender_unemployment_df["Unemployment Rate, Women, 16yo and over"].astype(float)
full_data= gender_unemployment_df["Unemployment Rate, 16yo and over"].astype(float)

#New clean DF
gender_unemployment_df= pd.DataFrame({"Year": years,"Male Unemployment Rate": male_data,
                                      "Female Unemployment Rate": female_data,
                                 "Unemployment Rate (Both Sexes)": full_data})

gender_unemployment_df.sort_values(by= "Year", ascending= True).reset_index(drop=True)
annual_data= gender_unemployment_df.groupby(["Year"])
annual_data= annual_data.mean().reset_index()

#Convert to tidy format

tidy_annual_df= pd.melt(annual_data, id_vars=['Year'], value_vars=['Male Unemployment Rate',
                                                   "Female Unemployment Rate", "Unemployment Rate (Both Sexes)"],

        var_name='Group', value_name='Unemployment Rate')
tidy_annual_df.to_csv("Combined_Ouput_File/gender_plot_data.csv", index=False)

# Race Statistics

In [ ]:
#Create race df
race_unemployment_df= unemployment_df[["Year","Unemployment Rate, 16yo and over",
                                       "Unemployment Rate, White, 16yo and over",
                                       "Unemployment Rate, African American, 16yo and over",
                                       "Unemployment Rate, Asian, 16yo and over",
                                       "Unemployment Rate, Hispanic or Latino, 16yo and over"]]

#Resort values and dtypes for data


r_years= race_unemployment_df["Year"].astype(int)
r_full_data= race_unemployment_df["Unemployment Rate, 16yo and over"].astype(float)
caucasian_data= race_unemployment_df["Unemployment Rate, White, 16yo and over"].astype(float)
black_data= race_unemployment_df["Unemployment Rate, African American, 16yo and over"].astype(float)
asian_data= race_unemployment_df["Unemployment Rate, Asian, 16yo and over"].astype(float)
hispanic_data= race_unemployment_df["Unemployment Rate, Hispanic or Latino, 16yo and over"].astype(float)

#New clean df
race_unemployment_df= pd.DataFrame({"Year": r_years,"Unemployment (All)": r_full_data, "Caucasian": caucasian_data,
                                   "Black or African American": black_data,
                                   "Asian": asian_data, "Hispanic": hispanic_data})
#Groupby year to gather mean
race_unemployment_df
race_unemployment_df.sort_values("Year", ascending=True).reset_index(drop=True)
r_annual_data= race_unemployment_df.groupby("Year")

unemployment_avg= r_annual_data["Unemployment (All)"].mean()
avgw_data= r_annual_data["Caucasian"].mean()
avgb_data= r_annual_data["Black or African American"].mean()
avga_data= r_annual_data["Asian"].mean()
avgh_data= r_annual_data["Hispanic"].mean()


avg_race_df= pd.DataFrame({"Unemployment (All)": unemployment_avg, "Caucasian":avgw_data, "Black or African American": avgb_data,
                     "Asian": avga_data, "Hispanic": avgh_data})
avg_race_df.reset_index(inplace=True)

#Convert to tidy format
r_tidy_annual_df= pd.melt(avg_race_df, id_vars=["Year"], value_vars=list(avg_race_df.columns)[1:],
                          var_name="Group",value_name="Unemployment Rate")
r_tidy_annual_df["Unemployment Rate"] = r_tidy_annual_df["Unemployment Rate"].map(lambda x: round(x,2) )

In [ ]:
r_tidy_annual_df.to_csv("Combined_Ouput_File/race_plot_data.csv",index=False)

In [152]:
for column in unemployment_agedf.columns[3:]:
    unemployment_agedf[f"{column}"] = unemployment_agedf[f"{column}"].astype(float)



unemployment_agedf.rename(columns={"Year": "years",
                           "LNS14000000":"Unemployment, 16yo and over",
                           "LNS14000001": "Unemployment, Men 16yo and over",
                           "LNS14000002": "Unemployment, Women 16yo and over",
                           "LNS14000003": "Unemployment, White people 16yo and over",
                           "LNS14000006": "Unemployment, African Americans 16yo and over",
                           "LNS14032183": "Unemployment, Asian people 16yo and over",
                           "LNS14000009": "Unemployment, Hispanic people 16yo and over"},
                                              inplace=True)
unemployment_agedf.reset_index(drop=True, inplace=True)

#unemployment_agedf.sort_values(by="years", ascending=True, inplace=True)

unemployment_agedf.head()

,years,months,"Unemployment, 16yo and over","Unemployment, Men 16yo and over","Unemployment, Women 16yo and over","Unemployment, White people 16yo and over","Unemployment, African Americans 16yo and over","Unemployment, Asian people 16yo and over","Unemployment, Hispanic people 16yo and over"
0,2018,December,3.9,3.9,3.8,3.4,6.6,3.3,4.4
1,2018,November,3.7,3.6,3.8,3.4,6.1,2.8,4.5
2,2018,October,3.8,3.8,3.8,3.3,6.3,3.1,4.4
3,2018,September,3.7,3.8,3.7,3.3,6.2,3.5,4.6
4,2018,August,3.8,3.8,3.8,3.4,6.3,3.0,4.7

In [153]:
unemployment_agedf.to_csv("Combined_Ouput_File/unemployment_agedf.csv")

In [154]:
age = unemployment_agedf[["years","Unemployment, 16yo and over", "Unemployment, Men 16yo and over", "Unemployment, Women 16yo and over", "Unemployment, White people 16yo and over",
                                  "Unemployment, African Americans 16yo and over","Unemployment, Asian people 16yo and over","Unemployment, Hispanic people 16yo and over"]]


year_groupby= age.groupby('years')["Unemployment, 16yo and over", "Unemployment, Men 16yo and over", "Unemployment, Women 16yo and over", "Unemployment, White people 16yo and over",
                                   "Unemployment, African Americans 16yo and over", "Unemployment, Asian people 16yo and over","Unemployment, Hispanic people 16yo and over"].mean()
year_groupby

,"Unemployment, Men 16yo and over","Unemployment, Women 16yo and over","Unemployment, White people 16yo and over","Unemployment, African Americans 16yo and over","Unemployment, Asian people 16yo and over","Unemployment, Hispanic people 16yo and over"
years,,,,,,
2006,4.608333,4.616667,4.033333,8.950000,3.050000,5.225000
2007,4.725000,4.500000,4.116667,8.258333,3.233333,5.641667
2008,6.141667,5.425000,5.191667,10.100000,3.950000,7.616667
2009,10.325000,8.075000,8.491667,14.783333,7.291667,12.083333
2010,10.491667,8.625000,8.716667,15.958333,7.500000,12.491667
2011,9.366667,8.458333,7.933333,15.825000,7.016667,11.491667
2012,8.216667,7.883333,7.191667,13.825000,5.900000,10.316667
2013,7.633333,7.075000,6.508333,13.066667,5.225000,9.108333
2014,6.258333,6.050000,5.300000,11.341667,4.983333,7.400000
2015,5.358333,5.183333,4.583333,9.558333,3.825000,6.600000
2016,4.950000,4.791667,4.283333,8.433333,3.641667,5.775000
2017,4.391667,4.316667,3.808333,7.483333,3.400000,5.133333
2018,3.941667,3.850000,3.458333,6.491667,3.000000,4.675000

In [155]:
change_inunemployment_rate = unemployment_agedf.loc[unemployment_agedf["months"]== "January"]
change_inunemployment_rate.sort_values(['years'],inplace= True)
change_inunemployment_rate.head()

C:\Users\Camilo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,years,months,"Unemployment, 16yo and over","Unemployment, Men 16yo and over","Unemployment, Women 16yo and over","Unemployment, White people 16yo and over","Unemployment, African Americans 16yo and over","Unemployment, Asian people 16yo and over","Unemployment, Hispanic people 16yo and over"
155,2006,January,4.7,4.6,4.8,4.1,8.9,3.0,5.5
143,2007,January,4.6,4.7,4.5,4.2,7.9,3.1,5.5
131,2008,January,5.0,5.2,4.8,4.4,9.1,3.1,6.3
119,2009,January,7.8,8.6,7.0,7.1,12.7,6.1,10.1
107,2010,January,9.8,11.0,8.4,8.8,16.5,8.3,12.9

In [156]:
change_inunemployment_rate['Unemployment, 16yo and over'] = change_inunemployment_rate['Unemployment, 16yo and over'].astype('float64')

C:\Users\Camilo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.